apiVersion: v1
kind: Service
metadata:
  name: devops-platform-service
spec:
  selector:
    app: devops-platform
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080